// Generated by `supabase gen types typescript --linked --schema public` on 2026-05-19
// against the remote project (mthxqkljhydguixsjvmr) AFTER the 6 winemine v0.1.0 migrations.
// Source of truth: production schema. Re-run after any future db push to keep types in sync.
// DO NOT EDIT BY HAND.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      cellar_items: {
        Row: {
          acquired_at: string
          consumed_at: string | null
          created_at: string | null
          id: string
          notes_en: string | null
          notes_ko: string | null
          notify_at_peak: boolean | null
          purchase_price_krw: number | null
          quantity: number
          status: string
          storage: string | null
          user_id: string
          wine_lwin: string
        }
        Insert: {
          acquired_at: string
          consumed_at?: string | null
          created_at?: string | null
          id?: string
          notes_en?: string | null
          notes_ko?: string | null
          notify_at_peak?: boolean | null
          purchase_price_krw?: number | null
          quantity?: number
          status?: string
          storage?: string | null
          user_id: string
          wine_lwin: string
        }
        Update: {
          acquired_at?: string
          consumed_at?: string | null
          created_at?: string | null
          id?: string
          notes_en?: string | null
          notes_ko?: string | null
          notify_at_peak?: boolean | null
          purchase_price_krw?: number | null
          quantity?: number
          status?: string
          storage?: string | null
          user_id?: string
          wine_lwin?: string
        }
        Relationships: [
          {
            foreignKeyName: "cellar_items_wine_lwin_fkey"
            columns: ["wine_lwin"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["lwin"]
          },
          {
            foreignKeyName: "cellar_items_wine_lwin_fkey"
            columns: ["wine_lwin"]
            isOneToOne: false
            referencedRelation: "wines_localized"
            referencedColumns: ["lwin"]
          },
        ]
      }
      feedback: {
        Row: {
          category: string
          created_at: string
          email: string | null
          id: string
          ip_address: string | null
          message: string
          user_agent: string | null
        }
        Insert: {
          category?: string
          created_at?: string
          email?: string | null
          id?: string
          ip_address?: string | null
          message: string
          user_agent?: string | null
        }
        Update: {
          category?: string
          created_at?: string
          email?: string | null
          id?: string
          ip_address?: string | null
          message?: string
          user_agent?: string | null
        }
        Relationships: []
      }
      follows: {
        Row: {
          created_at: string
          follower_id: string
          following_id: string
        }
        Insert: {
          created_at?: string
          follower_id: string
          following_id: string
        }
        Update: {
          created_at?: string
          follower_id?: string
          following_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follows_follower_id_fkey"
            columns: ["follower_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follows_following_id_fkey"
            columns: ["following_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          anonymous_display: string
          bio: string | null
          created_at: string | null
          email: string | null
          experience: string
          follower_count: number
          following_count: number
          handle: string | null
          id: string
          is_upgraded: boolean
          language: string
          level: number
          linked_providers: string[]
          mode: string
          public_countries_count: number
          public_notes_count: number
          public_regions_count: number
          public_wines_count: number
          theme: string
          updated_at: string | null
          xp: number
        }
        Insert: {
          anonymous_display: string
          bio?: string | null
          created_at?: string | null
          email?: string | null
          experience?: string
          follower_count?: number
          following_count?: number
          handle?: string | null
          id: string
          is_upgraded?: boolean
          language?: string
          level?: number
          linked_providers?: string[]
          mode?: string
          public_countries_count?: number
          public_notes_count?: number
          public_regions_count?: number
          public_wines_count?: number
          theme?: string
          updated_at?: string | null
          xp?: number
        }
        Update: {
          anonymous_display?: string
          bio?: string | null
          created_at?: string | null
          email?: string | null
          experience?: string
          follower_count?: number
          following_count?: number
          handle?: string | null
          id?: string
          is_upgraded?: boolean
          language?: string
          level?: number
          linked_providers?: string[]
          mode?: string
          public_countries_count?: number
          public_notes_count?: number
          public_regions_count?: number
          public_wines_count?: number
          theme?: string
          updated_at?: string | null
          xp?: number
        }
        Relationships: []
      }
      tasting_notes: {
        Row: {
          beginner_fields: Json | null
          created_at: string | null
          expert_fields: Json | null
          id: string
          location_text: string | null
          mode: string
          photo_url: string | null
          rating: number | null
          source: string | null
          tasted_at: string
          updated_at: string | null
          user_id: string
          wine_lwin: string
        }
        Insert: {
          beginner_fields?: Json | null
          created_at?: string | null
          expert_fields?: Json | null
          id?: string
          location_text?: string | null
          mode: string
          photo_url?: string | null
          rating?: number | null
          source?: string | null
          tasted_at?: string
          updated_at?: string | null
          user_id: string
          wine_lwin: string
        }
        Update: {
          beginner_fields?: Json | null
          created_at?: string | null
          expert_fields?: Json | null
          id?: string
          location_text?: string | null
          mode?: string
          photo_url?: string | null
          rating?: number | null
          source?: string | null
          tasted_at?: string
          updated_at?: string | null
          user_id?: string
          wine_lwin?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasting_notes_wine_lwin_fkey"
            columns: ["wine_lwin"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["lwin"]
          },
          {
            foreignKeyName: "tasting_notes_wine_lwin_fkey"
            columns: ["wine_lwin"]
            isOneToOne: false
            referencedRelation: "wines_localized"
            referencedColumns: ["lwin"]
          },
        ]
      }
      waitlist: {
        Row: {
          contact: string
          contact_type: string
          created_at: string
          id: string
          ip_address: string | null
          marketing_agree: boolean
          user_agent: string | null
        }
        Insert: {
          contact: string
          contact_type: string
          created_at?: string
          id?: string
          ip_address?: string | null
          marketing_agree?: boolean
          user_agent?: string | null
        }
        Update: {
          contact?: string
          contact_type?: string
          created_at?: string
          id?: string
          ip_address?: string | null
          marketing_agree?: boolean
          user_agent?: string | null
        }
        Relationships: []
      }
      wine_korean_names: {
        Row: {
          confidence: number | null
          country_match: boolean | null
          created_at: string | null
          id: number
          importer_num: number | null
          llm_model: string | null
          llm_reasoning: string | null
          lwin: string
          name_ko: string
          source: string
          source_url: string | null
        }
        Insert: {
          confidence?: number | null
          country_match?: boolean | null
          created_at?: string | null
          id?: number
          importer_num?: number | null
          llm_model?: string | null
          llm_reasoning?: string | null
          lwin: string
          name_ko: string
          source: string
          source_url?: string | null
        }
        Update: {
          confidence?: number | null
          country_match?: boolean | null
          created_at?: string | null
          id?: number
          importer_num?: number | null
          llm_model?: string | null
          llm_reasoning?: string | null
          lwin?: string
          name_ko?: string
          source?: string
          source_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "wine_korean_names_lwin_fkey"
            columns: ["lwin"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["lwin"]
          },
          {
            foreignKeyName: "wine_korean_names_lwin_fkey"
            columns: ["lwin"]
            isOneToOne: false
            referencedRelation: "wines_localized"
            referencedColumns: ["lwin"]
          },
        ]
      }
      wine_metadata: {
        Row: {
          bottle_color: string | null
          created_at: string | null
          drink_window_from_year: number | null
          drink_window_peak_year: number | null
          drink_window_to_year: number | null
          lwin: string
          type_canonical: string | null
          updated_at: string | null
          vintage_override: number | null
        }
        Insert: {
          bottle_color?: string | null
          created_at?: string | null
          drink_window_from_year?: number | null
          drink_window_peak_year?: number | null
          drink_window_to_year?: number | null
          lwin: string
          type_canonical?: string | null
          updated_at?: string | null
          vintage_override?: number | null
        }
        Update: {
          bottle_color?: string | null
          created_at?: string | null
          drink_window_from_year?: number | null
          drink_window_peak_year?: number | null
          drink_window_to_year?: number | null
          lwin?: string
          type_canonical?: string | null
          updated_at?: string | null
          vintage_override?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "wine_metadata_lwin_fkey"
            columns: ["lwin"]
            isOneToOne: true
            referencedRelation: "wines"
            referencedColumns: ["lwin"]
          },
          {
            foreignKeyName: "wine_metadata_lwin_fkey"
            columns: ["lwin"]
            isOneToOne: true
            referencedRelation: "wines_localized"
            referencedColumns: ["lwin"]
          },
        ]
      }
      wines: {
        Row: {
          classification: string | null
          country: string | null
          created_at: string | null
          display_name: string
          lwin: string
          producer_name: string | null
          producer_title: string | null
          region: string | null
          status: string | null
          type: string | null
          wine: string | null
        }
        Insert: {
          classification?: string | null
          country?: string | null
          created_at?: string | null
          display_name: string
          lwin: string
          producer_name?: string | null
          producer_title?: string | null
          region?: string | null
          status?: string | null
          type?: string | null
          wine?: string | null
        }
        Update: {
          classification?: string | null
          country?: string | null
          created_at?: string | null
          display_name?: string
          lwin?: string
          producer_name?: string | null
          producer_title?: string | null
          region?: string | null
          status?: string | null
          type?: string | null
          wine?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      profiles_public: {
        Row: {
          anonymous_display: string
          bio: string | null
          created_at: string | null
          follower_count: number
          following_count: number
          handle: string | null
          id: string
          level: number
          public_countries_count: number
          public_notes_count: number
          public_regions_count: number
          public_wines_count: number
        }
        Relationships: []
      }
      wines_localized: {
        Row: {
          bottle_color: string | null
          classification: string | null
          country: string | null
          display_name: string | null
          drink_window_from_year: number | null
          drink_window_peak_year: number | null
          drink_window_to_year: number | null
          lwin: string | null
          name_ko: string | null
          producer_name: string | null
          producer_title: string | null
          region: string | null
          status: string | null
          type_canonical: string | null
          type_raw: string | null
          vintage: number | null
          wine: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      anonymize: { Args: { user_id: string }; Returns: string }
      anonymize_index: {
        Args: { user_id: string }
        Returns: {
          adj_index: number
          noun_index: number
          num: number
        }[]
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
